-- 查詢1
-- 股票代碼為1210且市值比大於0.01的資料筆數
-- 尚未最佳化
SELECT CODE, COUNT(*)
FROM PROJECT2_TAIEX
WHERE MARKET_RATIO > 0.01
GROUP BY CODE
HAVING CODE = '1210';
-- 最佳化後
SELECT '1210' AS CODE, COUNT(*)
FROM PROJECT2_TAIEX
WHERE CODE='1210' AND MARKET_RATIO > 0.01;

-- ==========================================
-- 查詢2
-- 找出2018年，市淨率(PB)<1、市盈率<20且市值佔比>0.05的股票代碼以及日期
-- 尚未最佳化
SELECT CODE,DATE1
FROM PROJECT2_RESULT NATURAL JOIN PROJECT2_TAIEX
WHERE 
    EXTRACT(YEAR FROM DATE1) = 2018 
    AND PB<1 
    AND PE<20 
    AND MARKET_RATIO>0.05;
-- 最佳化後
SELECT PROJECT2_RESULT.CODE, PROJECT2_RESULT.DATE1
FROM PROJECT2_RESULT,PROJECT2_TAIEX
WHERE 
    PROJECT2_RESULT.CODE = PROJECT2_TAIEX.CODE 
    AND PROJECT2_RESULT.DATE1 = PROJECT2_TAIEX.DATE1 
    AND EXTRACT(YEAR FROM PROJECT2_RESULT.DATE1) = 2018 
    AND PROJECT2_RESULT.PB<1 
    AND PROJECT2_RESULT.PE<20 
    AND PROJECT2_TAIEX.MARKET_RATIO>0.05;

-- ==========================================
-- 查詢3
-- 股價淨值比<1且本益比<10的股票中，市值佔比最大的10筆資料
-- 尚未最佳化
SELECT RROJECT2_RESULT.CODE, PROJECT2_RESULT.DATE1, PROJECT2_RESULT.CLOSE,PROJECT2_RESULT.PB, PROJECT2_RESULT.PS, PROJECT2_TAIEX.MARKET_RATIO
FROM PROJECT2_RESULT
INNER JOIN PROJECT2_TAIEX ON PROJECT2_RESULT.CODE = PROJECT2_TAIEX.CODE AND PROJECT2_RESULT.DATE1 = PROJECT2_TAIEX.DATE1
WHERE
    REGEXP_LIKE(NVL(PROJECT2_RESULT.PB, '0'), '^\d+(\.\d+)?$')
    AND REGEXP_LIKE(NVL(PROJECT2_RESULT.PE, '0'), '^\d+(\.\d+)?$')
    AND TO_NUMBER(NVL(PROJECT2_RESULT.PB, '0')) < 1
    AND TO_NUMBER(NVL(PROJECT2_RESULT.PE, '0')) < 10
    AND TO_NUMBER(PROJECT2_TAIEX.MARKET_RATIO) IS NOT NULL
ORDER BY
    TO_NUMBER(PROJECT2_TAIEX.MARKET_RATIO) DESC
FETCH FIRST 10 ROWS ONLY;
-- 最佳化後
CREATE INDEX idx_code_date1_result ON PROJECT2_RESULT(CODE, DATE1);
CREATE INDEX idx_code_date1_taiex ON PROJECT2_TAIEX(CODE, DATE1);
CREATE INDEX idx_market_ratio_taiex ON PROJECT2_TAIEX(MARKET_RATIO);
CREATE INDEX idx_pb_result ON PROJECT2_RESULT(TO_NUMBER(PB));
SELECT PROJECT2_RESULT.CODE, PROJECT2_RESULT.DATE1, PROJECT2_RESULT.CLOSE,PROJECT2_RESULT.PB, PROJECT2_RESULT.PS, PROJECT2_TAIEX.MARKET_RATIO
FROM PROJECT2_RESULT
INNER JOIN PROJECT2_TAIEX ON PROJECT2_RESULT.CODE = PROJECT2_TAIEX.CODE AND PROJECT2_RESULT.DATE1 = PROJECT2_TAIEX.DATE1
WHERE
    REGEXP_LIKE(NVL(PROJECT2_RESULT.PB, '0'), '^\d+(\.\d+)?$')
    AND REGEXP_LIKE(NVL(PROJECT2_RESULT.PE, '0'), '^\d+(\.\d+)?$')
    AND TO_NUMBER(NVL(PROJECT2_RESULT.PB, '0')) < 1
    AND TO_NUMBER(NVL(PROJECT2_RESULT.PE, '0')) < 10
    AND TO_NUMBER(PROJECT2_TAIEX.MARKET_RATIO) IS NOT NULL
ORDER BY
    TO_NUMBER(PROJECT2_TAIEX.MARKET_RATIO) DESC
FETCH FIRST 10 ROWS ONLY;
